### ISSUE TITLE
Special characters not unbuilding correctly

### ISSUE THREAD

**Issue by tsijs** [qlik-oss/corectl#497] opened 2020-03-06 09:28 UTC
When variables contain special chars and super-subscripts, they will not be unbuild-build properly.

**Comment by glooms** [comment] 2020-03-09 10:08
Hi tsijs, could you provide steps to reproduce this behavior so I can have a look?

**Comment by glooms** [comment] 2020-03-23 09:32
@tsijs I tried with unicode sub/superscripts and special characters from the cyrillic alphabet and could not reproduce the error. I need more information about how this error was achieved in order to solve it.

Output after build + unbuild + build:
```
+--------------+-------+
|      ID      | Title |
+--------------+-------+
| variable-abc | x¹²³  |
| variable-xyz | x₀₁₂  |
+--------------+-------+
```

**Comment by glooms** [comment] 2020-03-25 11:43
Closing this issue, just reopen if you can provide information for reproducing.

**Closed by glooms** 2020-03-25 11:43 UTC

**Comment by tsijs** [comment] 2020-05-20 07:47
Thanks for the response, and sorry for taking this long to reply. For the sake of completeness of documentation: This issue occured for me for the titles of sheets. I won't have time to test this atm though, so leaving this closed for now is fine by me.
